version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
      - keycloak
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=my-realm
      - KEYCLOAK_CLIENT_ID=my-client
      - KEYCLOAK_CLIENT_SECRET=my-secret

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
    depends_on:
      - db
    command: start-dev

volumes:
  postgres_data: